# Gender Constant
GENDER = ('Male', 'Female', 'Other')

# Friend status constant
FRIEND_STATUS = ["IS_FRIEND", "REQUESTED", "REQUESTING", "BLOCKED"]
IS_FRIEND = "IS_FRIEND"
FRIEND_REQUESTING = "REQUESTING"
USER_BLOCKED = "BLOCKED"
