# Gender Constant
GENDER = ('Male', 'Female', 'Other')

# Friend status constant
FRIEND_STATUS = ["IS_FRIEND", "REQUESTED", "REQUESTING", "BLOCKED"]
IS_FRIEND = "IS_FRIEND"
FRIEND_REQUESTED_FROM = "REQUESTED"
FRIEND_REQUESTED_TO = "REQUESTING"
FRIEND_BLOCKED = "BLOCKED"
